### ISSUE TITLE
Atualizar logo

### ISSUE THREAD

**Issue by elvisdetona** [frontendweek/frontendweek-website#20]
Desenhar um logo mais genérico e atualizar no Layout

**Comment by matheusagcosta** [comment]
@elvisdetona me manda uns que voce curte pra eu ter uma ideia do seu genérico haha

**Comment by elvisdetona** [comment]
@matheusagcosta  Então ahahah, gosto pessoal: Só não pode ser verde ahaha... Mas esse site não é pra mim, é pra "comunidade front-end".  Eu só espero que seja algo sem o "ano" atrelado ao logo.... a idéia é "profissionalizar" isso e extender para outros estados / cidades do Brasil :D.  E vai ficar aberto pra qualquer um. Confio no seu bom gosto :D

**Comment by matheusagcosta** [comment]
@elvisdetona esqueci de responder, mas fechou! haha Vou mandar com o layout novo entao, daí vamos refinando por lá. 🍻
