### ISSUE TITLE
Atualizar stack

### ISSUE THREAD

**Issue by elvisdetona** [frontendweek/frontendweek-website#22]
Deixar simples para atualização... este projeto foi criado super rápido e não ligamos muito para a stack, mas agora, queremos deixar aberto para qualquer pessoa atualizar as informações e que seja super simples fazer o setup inicial.  

Lembrando que, o site é apenas um agregador de meetups e uma página estática resolve o problema.

**Comment by matheusagcosta** [comment]
@elvisdetona só HTML/CSS cruzao mesmo? Sem usar nada pra buildar?

**Comment by elvisdetona** [comment]
> @elvisdetona só HTML/CSS cruzao mesmo? Sem usar nada pra buildar?

Já ajuda montar uma nova estrutura, mas o ideal seria alguma coisa pra buildar isso aí...
Para o HTML acho que não precisa,
Para o CSS eu acho bom ter alguma coisa 
E no final, um gulpzão só mesmo resolve. 
Mas se for só o html/css, eu posso atualizar o site e depois eu automatizo isso :D

**Comment by matheusagcosta** [comment]
@elvisdetona Eu tenho usado o [harpjs](http://harpjs.com/) nos meus projetos estáticos e tem sido muito prático. É legal que ele aceita Sass, Less, Stylus, Jade/pug, markdown com zero configuração.

Da uma olhada no [repositório do meu site](https://github.com/matheusagcosta/matheusagcosta.github.io) como ficou e se achar válido posso fazer o setup aqui.

**Comment by elvisdetona** [comment]
@matheusagcosta Pode ser :D... Simples e prático.
